### ISSUE TITLE
Kampfticks verlängern. Auf 4 Ticks?!

### ISSUE THREAD

**Issue by SubStra88** [worp1900/newgame-issues#14]

**Comment by worp1900** [comment]
Da brauchts noch eine Weile hin. Der Umbau des Kampfsystems, den ich momentan mache, hat die notwendige Flexibilität um auch mehrere Ticks zu ermöglichen. Aber der Umbau braucht noch etwas, dann erstmal was mit Türmen und Bogenschützen, dann mal überlegen was wir dann machen.
Wenn es irgendwo einfach "mitzuerledigen" ist mach ichs, ansonsten muss es noch eine Weile warten.

**Comment by worp1900** [comment]
Seit heute eingebaut. Gibt noch einen Bug: Gibt man 5 Ticks als Angriffszeit an wird der Ankunftstick wird als eigener Tick gezählt und danach kommen nochmal 5 Ticks. D.h. Gesamtzahl 6 Angriffsticks. Ein Tick zu viel.

**Comment by worp1900** [comment]
> Seit heute eingebaut. Gibt noch einen Bug: Gibt man 5 Ticks als Angriffszeit an wird der Ankunftstick wird als eigener Tick gezählt und danach kommen nochmal 5 Ticks. D.h. Gesamtzahl 6 Angriffsticks. Ein Tick zu viel.

Sollte gefixt sein.
