### ISSUE TITLE
Bauzeit der Truppen erhöhen

### ISSUE THREAD

**Issue by SubStra88** [worp1900/newgame-issues#15]
Auf 3 oder 4 Stunden?
Ich präferiere 4 weils die Angriffszeit ist.

**Comment by worp1900** [comment]
Wir brauchen ein reaktives Element. Sonst kann man nur zuschauen wenn man angegriffen wird und es nicht vorher oder mindestens zeitgleich gemerkt hat. Über 2h würde ich also nicht gehen.
Frag mal die Jungs und Mädels was sie wollen, Umfrage oder so. Dann setzen wir es zum nächsten Reset auf den gewünschten Wert.

**Comment by worp1900** [comment]
Potentiell könnten wir auch die Laufzeit wieder kürzer machen, solange wir nur einen Kampftick haben. Evtl. Laufzeit auf 3h, Bauzeit dort lassen wo sie ist => Reaktionszeit = 2h.

**Comment by SubStra88** [comment]
Ich würde die Angriffszeit lassen. Die ist okay. Bauzeit Wachs/Räuber dann auf 2h?!
Sobald es Türme gibt, bzw. Bogenschützen, könnte man diese vllt als kurze Reaktion nehmen. 1,5 Stunden oder 2. Dann Wachen/Räuber auf 3 oder 4 Stunden erhöhen?!

**Comment by worp1900** [comment]
> Ich würde die Angriffszeit lassen. Die ist okay. Bauzeit Wachs/Räuber dann auf 2h?!
> Sobald es Türme gibt, bzw. Bogenschützen, könnte man diese vllt als kurze Reaktion nehmen. 1,5 Stunden oder 2. Dann Wachen/Räuber auf 3 oder 4 Stunden erhöhen?!

Yes, sobald es Archers und Towers gibt sind die definitiv das reaktive Element. Zumindest die Bogenschützen.

Mach mal eine Umfrage im Channel wie wir die Attzeit und die Bauzeit für Raider/Guards für nächste Runde wollen. Vrstl. gibt es nächste Runde noch keine Türme/ Bogenschützen, sondern gemeinsames Angreifen/Verteidigen, weil das Kampfsystem grundsätzliche Überarbeitung braucht.

D.h. wie soll die Bauzeit und Laufzeit nächste Runde sein, wenn man gemeinsam angreifen und verteidigen kann? Das bräuchte ich als Input von "der Community" bitte.

**Comment by worp1900** [comment]
Denke das hat sich erledigt :)
