### ISSUE TITLE
Angriff aufs eigene Dorf

### ISSUE THREAD

**Issue by SubStra88** [worp1900/newgame-issues#18]
Angriffe auf sich selbst sind möglich. Angriffszeit wird ganz normal genutzt (4 Stunden). Bei "Ankunft" wird kein KB erzeugt. Die Armee hat keinen "Rückweg"

**Comment by SubStra88** [comment]
![image](https://user-images.githubusercontent.com/72553194/100229301-523d2880-2f24-11eb-93c5-b8baf0de0f5a.png)

**Comment by heulwurf** [comment]
Mit dem neuen Kampfsystem wird ein KB erzeugt - Armee ist aber trotzdem instant zuhause
