### ISSUE TITLE
Dorfverteidigung nicht korrekt

### ISSUE THREAD

**Issue by SubStra88** [worp1900/newgame-issues#2]
Ich greife an. Bevor ich ankomme, werde ich von diesem Spieler selber angegriffen. 
In meinem KB (mein Angriff) steht die Dorfverteidigung mit 1299 Räubern. Das heißt für mich, dass diese zuhause sind. 
Sobald ich angegriffen werde, tauchen diese 1299 bei mir im Dorf auf. Ehrlicj gesagt habe ich damit gerechnet, dass es ein Spy Besuch mit 1 Einheit ist...
Siehe Screenshots

**Comment by worp1900** [comment]
Wird mit #16 mit-erledigt.
