### ISSUE TITLE
KB bei Rückkehr von Truppen

### ISSUE THREAD

**Issue by heulwurf** [worp1900/newgame-issues#25]
Ablauf:
Truppen führen Aktion aus (vermutlich Angriff)

Erwartetes Ergebnis:

Truppen kommen nachhause und keine weitere Aktion entsteht

Tatsächliches Ergebnis:
Truppen erzeugen bei Rückkehr im eigenen "Dorf" einen KB (es werden sogar Gens gestohlen)

**Comment by heulwurf** [comment]
Screenshot [https://www.dropbox.com/s/csbas3f900eedbo/200123300595_285981.jpg?dl=0](url)

**Comment by heulwurf** [comment]
https://www.dropbox.com/s/urcagrw5sf3ebqw/200119900287_291141.jpg?dl=0

**Comment by worp1900** [comment]
Ich kann das nicht reproduzieren. Brauche bitte eine Beschreibung wie man vorgehen muss um dieses Verhalten zu bekommen.

**Comment by worp1900** [comment]
Ich schließe den Issue einstweilen. Bitte gerne wieder öffnen wenn man es reproduzieren kann.
