### ISSUE TITLE
Kampfbericht Zeit stimmt nicht

### ISSUE THREAD

**Issue by heulwurf** [worp1900/newgame-issues#26]
Die Zeitren der Kampfberichte stimmen nicht

Erwartung:
Es wird der Zeitpunkt des Kampfes im KB ausgegeben

Ist: 
Es wird der Zeitpunkt an dem der Angriff beginn (loslaufen) ausgegeben

**Comment by SubStra88** [comment]
Ich glaub das ist behoben oder? Bei meinen KBs werden die korrekten Zeiten angegeben

**Comment by heulwurf** [comment]
![Screenshot_20210127-123846](https://user-images.githubusercontent.com/10299443/106020949-92578d80-60c4-11eb-8d8b-075f84388e6c.jpg)
Bei mir nach wie vor nicht

**Comment by SubStra88** [comment]
![image](https://user-images.githubusercontent.com/72553194/106052805-5505f680-60ea-11eb-8eb9-317c77dac743.png)

Ich glaube du hast Recht. Ich hab nicht genau genug drauf geachtet. Die Zeiten verändern sich zwar. Aber die Zeit ist verschoben. Ich glaube meine Angreifer waren heute un 17:14 bei mir angekommen. 
Ich muss da morgen nochmal genau drauf achten wann die Armee dann ankommt und welche Zeit der KB hat

**Comment by SubStra88** [comment]
![image](https://user-images.githubusercontent.com/72553194/106192590-af678b80-61ac-11eb-9b17-e4cbdddab24c.png)
Der letzte KB scheint unmittelbar nach der ursprünglichen Ankunft der Armee zeitlich zu sein. Warum auch immer werden die KBs zeitlich 5 Ticks zurückgerechnet?!
Aber es scheint nicht die Zeit zu sein in der die Armeen losmarschiert sind.

**Comment by worp1900** [comment]
Die Zeit in KBs scheint grundsätzlich eine Stunde zu früh angezeigt zu werden.
Unser Einschlag bei Don war heute 16:15, erster KB zeigt 15:15 als Uhrzeit. Genau eine Stunde früher als Einschlag war.
