### ISSUE TITLE
V wechseln die Seite

### ISSUE THREAD

**Issue by heulwurf** [worp1900/newgame-issues#27]
Vorbedingung:
Truppe mit allen S von AWG auf Rückkehr zum Dorf
Elena greift in diese Zeit AWG mit S an

Erwartetes Ergebnise:
Elena greift an und V verteidigen gegen die S

Eingetretenes Ergebnis:
Elena greift an die V, schließen sich den marodierenden gegnerischen S an und plündern das Dorf. Beute wird geteilt (50% Gens bleiben im Dorf
![200171400872_1628](https://user-images.githubusercontent.com/10299443/102131795-07dc0700-3e53-11eb-93d8-fe797d2e1ce6.jpg)

**Comment by heulwurf** [comment]
Weiteres Update: Geht bei AWG immer dann, wenn er nicht alle S/V in seine Truppen verteilt hat, sondern noch freie im Dorf stehen hat

**Comment by worp1900** [comment]
Krieg ich nicht reproduziert, brauche bitte eine Step-by-Step Anleitung wie ich das nachstellen könnte.

Hab angegriffen, verteidigt, bin zurück gekommen, und verschiedene Kombinationen davon (während mich jmd. anderes angreift). Aber das sah aus wie es soll.
