### ISSUE TITLE
https aktivieren

### ISSUE THREAD

**Issue by btmd** [worp1900/newgame-issues#47]
Die Seite muss ueber https:// erreichbar sein, sonst meckern alle Browser immer
Ausserdem Passwoerter

**Comment by worp1900** [comment]
Fast erledigt, noch sind Formulare unsicher, aber da bin ich dran.

**Comment by btmd** [comment]
https://stackoverflow.com/questions/28552788/laravel-form-https-action

Ich denke, wir müssen in src/routes/web.php
alles zwischen Zeile  25 und 77 einrahmen von

Route::group(array('https'), function() {
... Zeile 25 - Zeile 77
})

**Comment by worp1900** [comment]
Erledigt!
