### ISSUE TITLE
Leeren Armeen verursachen weiterhin einen KB

### ISSUE THREAD

**Issue by SubStra88** [worp1900/newgame-issues#55]
Armeen die genullt werden haben trotzdem vollen Aufenthalt (außer sie werden recalled) und laufen auch den vollen weg zurück, auch wenn sie 0 Einheiten drin haben.
Auch das wird noch geändert.

**Comment by worp1900** [comment]
Sollte mit worp1900/norsetribes#78 gelöst sein.
Falls da noch etwas auftaucht bitte diesen Issue wieder öffnen.
