### ISSUE TITLE
Im Kampfbericht kämpfen nicht alle Einheiten?!

### ISSUE THREAD

**Issue by SubStra88** [worp1900/newgame-issues#60]
Warum killen die Berserker von Erikson nicht meine Kämpfer? 
![74225A72-C8ED-4696-8549-6886FEF9BB20](https://user-images.githubusercontent.com/72553194/125838375-8aa22418-1f90-481a-b9ca-83775e19374c.png)

**Comment by worp1900** [comment]
Sollte mit dem neuen Kampfsystem weg sein.
