### ISSUE TITLE
Kampfberechnung fehlerhaft?

### ISSUE THREAD

**Issue by SubStra88** [worp1900/newgame-issues#61]
Habe 100k Kämpfer geschickt. Gegner hat fast 70k Bogenschützen und knapp 140k Miliz. 
Nach meinem Verständnis und nach dem Kampfsystem sollten 40k Bogis und und 180k Miliz geschroteter werden. Es wurden aber alle Bogis und alle Miliz geschrottet. Ich hätte erwartet, dass knapp 30k Bogis übrig bleiben!? 
Screenshot anbei. 
![B5A92B53-82D3-4CD5-8196-9A8E51C49A94](https://user-images.githubusercontent.com/72553194/126299782-6ee7614b-eb07-4ee5-bfb6-a78dbc82c783.png)

**Comment by worp1900** [comment]
Sollte mit dem neuen Kampfsystem weg sein.
